### ISSUE TITLE
Reverse proxy feature request

### ISSUE THREAD

**Issue by Eternumkr** [CodyTseng/nostr-relay-nestjs#388]
I cant seem to connect to the relay i setup. the IP address works but the Domain name doesnt. I am using not docker setup.

Can you please add some tips or tutorial for using a reverse proxy? 

Thank you.

**Comment by CodyTseng** [comment]
Hi @Eternumkr , If you can successfully access the service via IP, it indicates that the error lies between the DNS service and your server. You need to check if the DNS is configured correctly. If you're using Cloudflare, here's their relevant documentation: https://developers.cloudflare.com/dns/

I hope my response helps you.

**Comment by Eternumkr** [comment]
That is the part im confused on. my domain wont point to "address:3000" it only points to "address".

**Comment by CodyTseng** [comment]
You can use a service like NGINX to proxy requests from port 80 (or 443) to port 3000

**Comment by Eternumkr** [comment]
server {
    server_name server-name;

    location / {
        proxy_pass http://0.0.0.0:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

putting this into a config file for nginx then using certbot for ssl worked for me. 
ill leave this for anyone who needs it.
